#![no_std]
#![no_main]

// All of the actual hooks are declared in the generated and hooks modules.
// The generated module contains code which is autogenerated by the build.rs
// script given the list of postgres functions to attach to, as declared in
// the shared crate at src/postgres_funcs.rs. The hooks in the generated
// module are thin wrappers around the event submission functions in the hooks
// module. The hooks module also contains some special hooks for the top
// level postgres functions because they require special handling.
mod generated;
mod hooks;

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    unsafe { core::hint::unreachable_unchecked() }
}
