// Include the list of postgres functions to attach to.
// The hooks for these functions are autogenerated by the build.rs script
// in the kernelspace-ebpf-tracer crate.
// We include them here so that we know which functions to attach to in the
// userspace collector.
include!("../../shared/src/postgres_funcs.rs");
