name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        id: cache-docker-layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-postgres
          restore-keys: |
            ${{ runner.os }}-postgres

      - name: Load Docker cache
        if: steps.cache-docker-layers.outputs.cache-hit == 'true'
        run: docker load -i /tmp/.buildx-cache/docker-image.tar

      - name: Run Postgres build script
        run: ./ci-build-postgres.sh ${{ steps.cache-docker-layers.outputs.cache-hit }}

      - name: Save Docker image
        run: docker save pg-ferret-postgres-16:latest -o /tmp/.buildx-cache/docker-image.tar

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-postgres

      - name: Logout from Docker Hub
        run: docker logout
