name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        id: cache-docker-layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker
          restore-keys: |
            ${{ runner.os }}-docker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build postgres
      - name: Load Postgres cache
        run: |
          if [ -f /tmp/.buildx-cache/postgres.tar ]; then
            docker load -i /tmp/.buildx-cache/postgres.tar
          else
            echo "Postgres cache not found, proceeding without it"
          fi

      - name: Run Postgres build script
        run: ./ci-build-postgres.sh

      - name: Push Postgres image to Docker Hub
        run: |
          docker tag pg-ferret-postgres-16:latest ${{ secrets.DOCKER_USERNAME }}/pg-ferret-postgres-16:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pg-ferret-postgres-16:latest

      - name: Save Postgres Docker image
        run: docker save pg-ferret-postgres-16:latest -o /tmp/.buildx-cache/postgres.tar

      # Build PG Ferret
      - name: Load PG Ferret cache
        run: |
          if [ -f /tmp/.buildx-cache/pg-ferret.tar ]; then
            docker load -i /tmp/.buildx-cache/pg-ferret.tar
          else
            echo "PG Ferret cache not found, proceeding without it"
          fi

      - name: Build Docker image with pg-ferret-postgres-16 base
        run: docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache,mode=max --tag ${{ secrets.DOCKER_USERNAME }}/pg-ferret:latest --push .

      - name: Save PG Ferret Docker image
        run: docker save ${{ secrets.DOCKER_USERNAME }}/pg-ferret:latest -o /tmp/.buildx-cache/pg-ferret.tar

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker
          restore-keys: |
            ${{ runner.os }}-docker

      - name: Logout from Docker Hub
        run: docker logout
