name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            architecture: amd64
          - os: macos-latest
            architecture: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build postgres image
      - name: Run Postgres build script
        run: ./ci-build-postgres.sh

      - name: Push Postgres image to Docker Hub
        run: |
          docker tag pg-ferret-postgres-16:latest ${{ secrets.DOCKER_USERNAME }}/pg-ferret-postgres-16:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pg-ferret-postgres-16:latest

      # Build pg-ferret image
      - name: Build Docker image with pg-ferret-postgres-16 base
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} --tag ${{ secrets.DOCKER_USERNAME }}/pg-ferret:latest --push .

      - name: Logout from Docker Hub
        run: docker logout
