name: Build and Cache Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}-
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          #file: Dockerfile.test
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pg-ferret:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Build pg-ferret image
      # - name: Build Docker image with pg-ferret-postgres-16 base
      #   run: |
      #     docker buildx build \
      #       --platform linux/${{ matrix.architecture }} \
      #       --cache-from type=local,src=/tmp/.buildx-cache \
      #       --cache-to type=local,dest=/tmp/.buildx-cache-new \
      #       --tag pg-ferret:temp .
      #     docker tag pg-ferret:temp ${{ secrets.DOCKER_USERNAME }}/pg-ferret:${{ matrix.architecture }}
      #     docker push ${{ secrets.DOCKER_USERNAME }}/pg-ferret:${{ matrix.architecture }}

      - name: Verify multi-architecture image
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/pg-ferret:latest uname -m
